import { initializePuppeteerDeno } from './src/initialize-deno.ts';

export const puppeteer = initializePuppeteerDeno('puppeteer-core');
export default puppeteer;

export * from './src/Accessibility.ts';
export * from './src/Browser.ts';
export * from './src/BrowserFetcher.ts';
export * from './src/Connection.ts';
export * from './src/ConsoleMessage.ts';
export * from './src/Coverage.ts';
export * from './src/DeviceDescriptors.ts';
export * from './src/Dialog.ts';
export * from './src/DOMWorld.ts';
export * from './src/JSHandle.ts';
export * from './src/ExecutionContext.ts';
export * from './src/EventEmitter.ts';
export * from './src/FileChooser.ts';
export * from './src/FrameManager.ts';
export * from './src/Input.ts';
export * from './src/Page.ts';
export * from './src/Product.ts';
export * from './src/Puppeteer.ts';
export * from './src/PuppeteerDeno.ts';
export * from './src/BrowserConnector.ts';
export * from './src/Launcher.ts';
export * from './src/LaunchOptions.ts';
export * from './src/HTTPRequest.ts';
export * from './src/HTTPResponse.ts';
export * from './src/SecurityDetails.ts';
export * from './src/Target.ts';
export * from './src/Errors.ts';
export * from './src/Tracing.ts';
export * from './src/NetworkManager.ts';
export * from './src/WebWorker.ts';
export * from './src/USKeyboardLayout.ts';
export * from './src/EvalTypes.ts';
export * from './src/PDFOptions.ts';
export * from './src/TimeoutSettings.ts';
export * from './src/LifecycleWatcher.ts';
export * from './src/QueryHandler.ts';
export type { Protocol } from './vendor/devtools-protocol/protocol.d.ts';
